version: '3.8'

services:
  db:
    environment:
      - POSTGRES_PASSWORD
      - PGPASSWORD=$POSTGRES_PASSWORD
    command: >-
      postgres
          -c 'log_duration=on'
          -c 'log_statement=all'

  backend:
    user: '0:0' # This is due to shared docker volume permissions.
    environment:
      - DJANGO_SETTINGS_MODULE=ams.settings
      - DJANGO_SECRET_KEY
      - DJANGO_CONFIGURATION
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - DEFAULT_FROM_EMAIL
      - APPLICATION_WEB_HOST
      - APPLICATION_VERSION
      - APPLICATION_DB_HOST
      - APPLICATION_DB_NAME
      - APPLICATION_DB_USER
      - APPLICATION_DB_PASSWORD
      - PGPASSWORD=$POSTGRES_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - SENTRY_DSN
    volumes:
      - static_data:/src/app/static

  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf
      - .htpasswd:/etc/nginx/.htpasswd
      - /etc/letsencrypt:/etc/letsencrypt
      - static_data:/usr/share/nginx/static:ro

volumes:
  static_data:
