version: '3.8'

services:
  db:
    environment:
      - POSTGRES_PASSWORD
      - PGPASSWORD=$POSTGRES_PASSWORD
    command: >-
      postgres
          -c 'log_duration=on'
          -c 'log_statement=all'

  backend:
    environment:
      - DJANGO_SETTINGS_MODULE=ams.settings
      - DJANGO_SECRET_KEY
      - DJANGO_CONFIGURATION
      - APPLICATION_WEB_HOST
      - APPLICATION_VERSION
      - APPLICATION_DB_HOST
      - APPLICATION_DB_NAME
      - APPLICATION_DB_USER
      - APPLICATION_DB_PASSWORD
      - PGPASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./backend/ams/settings.py:/src/app/ams/settings.py

  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-test.conf:/etc/nginx/conf.d/default.conf
      - .htpasswd:/etc/nginx/.htpasswd
      - /etc/letsencrypt:/etc/letsencrypt
