site_name: Association Management System Documentation
repo_url: https://github.com/digital-technologies-teachers-aotearoa/ams
repo_name: AMS on GitHub

theme:
  name: material
  custom_dir: overrides
  features:
    - toc.follow
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
extra_css:
  - assets/stylesheets/main.css

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
    # permalink: true

nav:
  - Home: index.md
  - User guide:
      - user/index.md
  - Website administrator guide:
      - admin/index.md
      - admin/cms.md
      - admin/forum.md
      - admin/theme-customization.md
  - Developer documentation:
      - developer/contributing.md
      - developer/billing.md
      - developer/management-commands-catalog.md
      - developer/forum.md
      - developer/icons.md
      - developer/urls.md
      - developer/permission-caching.md
      - developer/deployment.md
      - developer/wagtail-cms.md
      - developer/theme-system.md
