name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['main']

  push:
    branches: ['main']

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  project-lint:
    name: Run project linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  django-test:
    name: Run Django tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache local backend
        uses: docker/bake-action@v6
        with:
          push: false
          load: true
          files: docker-compose.yml
          targets: django
          set: |
            django.cache-from=type=gha,scope=django-cached-tests
            django.cache-to=type=gha,scope=django-cached-tests,mode=max
            node.cache-from=type=gha,scope=node-cached-tests
            node.cache-to=type=gha,scope=node-cached-tests,mode=max

      - name: Check database migrations
        run: docker compose run --rm django python manage.py makemigrations --check

      - name: Run database migrations
        run: docker compose run --rm django python manage.py migrate

      - name: Run Django tests
        run: docker compose run django pytest

      - name: Teardown
        run: docker compose down

  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Build MkDocs documentation
        run: docker compose run --rm docs build

  publish-image:
    name: Build and push image
    runs-on: ubuntu-latest
    needs: [project-lint, django-test, build-docs]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Django image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: compose/production/django/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-django:latest
            ghcr.io/${{ github.repository }}-django:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha,scope=django
          cache-to: type=gha,scope=django,mode=max

      - name: Deploy to DigitalOcean App Platform (ams-dev)
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_DEPLOY_TOKEN }}
          app_name: ams-dev-website
          print_build_logs: true
          print_deploy_logs: true
        env:
          IMAGE_DIGEST_DJANGO: ${{ steps.push.outputs.digest }}
          IMAGE_DIGEST_JOB-DEPLOY: ${{ steps.push.outputs.digest }}

  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: [project-lint, django-test, build-docs]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Build MkDocs documentation
        run: docker compose run --rm docs build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
